name: Checkout PyTorch

description: Clean workspace and check out PyTorch

runs:
  using: composite
  steps:
    - name: Clean workspace
      shell: bash
      run: |
        echo "${GITHUB_WORKSPACE}"
        rm -rf "${GITHUB_WORKSPACE}"
        mkdir "${GITHUB_WORKSPACE}"

    - name: Checkout PyTorch
      uses: zhouzhuojie/checkout@05b13c9a0d21f08f6d5e64a1d5042246d13619d9
      with:
        ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
        # deep clone, to allow use of git merge-base
        fetch-depth: 0
        submodules: recursive
