# https://travis-ci.org/pytorch/pytorch
language: python
dist: trusty
git:
  submodules: false

# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
    fast_finish: true
    include:
      - env: LINT_CHECK
        python: "2.7"
        install: pip install flake8
        script: flake8
      - env: LINT_CHECK
        python: "3.7"
        dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
        sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
        install: pip install flake8
        script: flake8
      - env: MYPY_TYPE_CHECK
        python: "3.6"
        install: pip install mypy mypy-extensions
        script: mypy @mypy-files.txt
      - env: CPP_DOC_CHECK
        install: sudo apt-get install -y doxygen
        script: cd docs/cpp/source && ./check-doxygen.sh
      - env: CLANG_TIDY
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-trusty-6.0
            packages: clang-tidy-6.0
        before_script:
          - mkdir clang-tidy-build
          - cd clang-tidy-build
          - cmake -DBUILD_TORCH=ON ..
          - cd ..
        script: python tools/clang_tidy.py --verbose \
          -c $(which clang-tidy-6.0) -d clang-tidy-build -p torch/csrc -r .
