

before_install: 
  - pip install codecov 
  - pip install coverage

install: true

script: 
  - coverage run main.py
  - node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
  - codecov
cache:
  directories:
    - node_modules
after_success:
  - bash <(curl -s https://codecov.io/bash)
