# https://travis-ci.org/zdevito/ATen
language: python
python:
    - 2.7
    - 3.6

dist: trusty

before_install:
  - sudo apt-get install -qq valgrind 
  - pip install codecov 
  - pip install coverage
  
install:
    - travis_retry pip install pyyaml typing
   

script:
    - cd aten
    - mkdir build install
    - cd build
    - cmake .. -DUSE_CUDA=OFF -DCMAKE_INSTALL_PREFIX=../install
    - make install
    - ../tools/run_tests.sh .
    - cd ..
    - tools/test_install.sh $(pwd)/install $(pwd)
    - coverage run main.py
    - coverage run main.py
    - node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
    - codecov   
    
matrix:
    fast_finish: true
    include:
        env: LINT_CHECK
        python: "2.7"
        install: pip install flake8-mypy
        script: flake8
        
after_success:
  - cd Tests/
  - bash <(curl -s https://codecov.io/bash) -t 8faabb77-d745-44bc-be18-b906de8e2928
  - codecov -f "coverage.xml"


