# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    set +x
    sudo pip -q install awscli==1.16.35
    export AWS_ACCESS_KEY_ID=${ACCESS_KEY_ID}
    export AWS_SECRET_ACCESS_KEY=${SECRET}
    eval $(aws ecr get-login --region us-east-1 --no-include-email)
    echo "DOCKER_IMAGE: "${DOCKER_IMAGE}
    docker pull ${DOCKER_IMAGE}
    export id=$(docker run -t -d -w /var/lib/jenkins ${DOCKER_IMAGE})

    echo "id: "$id
  env:
    ACCESS_KEY_ID: $(ECR_ACCESS_KEY_ID)
    SECRET: $(ECR_SECRET)
    DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-trusty-py3.5:300"
  displayName: 'try aws stuff'
