# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

container:
  image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-trusty-py3.5:300
  endpoint: aws_docker
  options: -u 0

steps:
- bash: |
    set +x
    .jenkins/pytorch/build.sh
  env:
    ACCESS_KEY_ID: $(ECR_ACCESS_KEY_ID)
    SECRET: $(ECR_SECRET)
    DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-trusty-py3.5:300"
  displayName: 'try aws stuff'
