# binary linux build defaults
##############################################################################
binary_linux_build: &binary_linux_build
  resource_class: 2xlarge+
  steps:
  - run:
      <<: *binary_populate_env
  - run:
      <<: *binary_checkout
  - run:
      name: Install unbuffer and ts
      command: |
        set -ex
        source /env
        retry yum -q -y install epel-release
        retry yum -q -y install expect moreutils
  - run:
      name: Upgrade gcc version (based on env var)
      command: |
        set -ex
        source /env
        if [[ "$DESIRED_DEVTOOLSET" == 'devtoolset7' ]]; then
          /builder/upgrade_gcc_abi.sh
        else
          echo "Not upgrading gcc version"
        fi
  - run:
      name: Build
      no_output_timeout: "1h"
      command: |
        source "/pytorch/.circleci/scripts/binary_linux_build.sh"
  - persist_to_workspace:
      root: /
      paths: final_pkgs


# This should really just be another step of the binary_linux_build job above.
# This isn't possible right now b/c the build job uses the docker executor
# (otherwise they'd be really really slow) but this one uses the macine
# executor (b/c we have to run the docker with --runtime=nvidia and we can't do
# that on the docker executor)
binary_linux_test: &binary_linux_test
  machine:
    image: ubuntu-1604:201903-01
  steps:
  - run:
      <<: *setup_linux_system_environment
  - run:
      <<: *setup_ci_environment
  - attach_workspace:
      at: /home/circleci/project
  - run:
      <<: *binary_populate_env
  - run:
      name: Prepare test code
      no_output_timeout: "1h"
      command: |
        if [[ -n "$CIRCLE_SHA1" ]]; then
          # we are on a PR or on a master-merge, but not on a timed build
          git_url="https://raw.githubusercontent.com/pytorch/pytorch/$CIRCLE_SHA1"
        else
          # scheduled nightly binary builds. These run at 05:05 UTC every day. 
          last_commit="$(git rev-list --before "$(date -u +%Y-%m-%d) 05:00" --max-count 1 HEAD)"
          git_url="https://raw.githubusercontent.com/pytorch/pytorch/$last_commit"
        fi
        curl -s "$git_url/.circleci/scripts/binary_linux_test.sh" -o "binary_linux_test.sh"
        cat "binary_linux_test.sh"
        source "binary_linux_test.sh"
  - run:
      <<: *binary_run_in_docker

binary_linux_upload: &binary_linux_upload
  machine:
    image: ubuntu-1604:201903-01
  steps:
  - run:
      <<: *setup_linux_system_environment
  - run:
      <<: *setup_ci_environment
  - attach_workspace:
      at: /home/circleci/project
  - run:
      <<: *binary_populate_env
  - run:
      <<: *binary_install_miniconda
  - run:
      name: Upload
      no_output_timeout: "10m"
      command: |
        if [[ -n "$CIRCLE_SHA1" ]]; then
          # we are on a PR or on a master-merge, but not on a timed build
          git_url="https://raw.githubusercontent.com/pytorch/pytorch/$CIRCLE_SHA1"
        else
          # scheduled nightly binary builds. These run at 05:05 UTC every day. 
          last_commit="$(git rev-list --before "$(date -u +%Y-%m-%d) 05:00" --max-count 1 HEAD)"
          git_url="https://raw.githubusercontent.com/pytorch/pytorch/$last_commit"
        fi
        curl -s "$git_url/.circleci/scripts/binary_linux_upload.sh" -o "binary_linux_upload.sh"
        cat "binary_linux_upload.sh"
        source "binary_linux_upload.sh"
