

##############################################################################
# Linux build defaults
##############################################################################

pytorch_linux_build_defaults: &pytorch_linux_build_defaults
  resource_class: large
  machine:
    image: default
  steps:
  - run:
      <<: *setup_linux_system_environment
  - run:
      <<: *install_official_git_client
  - checkout
  - run:
      <<: *setup_ci_environment
  - run:
      name: Build
      no_output_timeout: "1h"
      command: |
        set -x
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls
        .circleci/shell-scripts/pytorch_linux_build_defaults.sh


pytorch_linux_test_defaults: &pytorch_linux_test_defaults
  machine:
    image: default
  steps:
  - run:
      <<: *setup_linux_system_environment
  - run:
      <<: *setup_ci_environment
  - run:
      name: Test
      no_output_timeout: "90m"
      command: |
        set -x
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls
        .circleci/shell-scripts/pytorch_linux_test_defaults.sh


caffe2_linux_build_defaults: &caffe2_linux_build_defaults
  resource_class: large
  machine:
    image: default
  steps:
  - run:
      <<: *setup_linux_system_environment
  - run:
      <<: *install_official_git_client
  - checkout
  - run:
      <<: *setup_ci_environment
  - run:
      name: Build
      no_output_timeout: "1h"
      command: |
        set -x
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls
        .circleci/shell-scripts/caffe2_linux_build_defaults.sh


caffe2_linux_test_defaults: &caffe2_linux_test_defaults
  machine:
    image: default
  steps:
  - run:
      <<: *setup_linux_system_environment
  - run:
      <<: *setup_ci_environment
  - run:
      name: Test
      no_output_timeout: "1h"
      command: |
        set -x
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls
        .circleci/shell-scripts/caffe2_linux_test_defaults.sh

