
##############################################################################
# Binary build (nightlies nightly build) defaults
# The binary builds use the docker executor b/c at time of writing the machine
# executor is limited to only two cores and is painfully slow (4.5+ hours per
# GPU build). But the docker executor cannot be run with --runtime=nvidia, and
# so the binary test/upload jobs must run on a machine executor. The package
# built in the build job is persisted to the workspace, which the test jobs
# expect. The test jobs just run a few quick smoke tests (very similar to the
# second-round-user-facing smoke tests above) and then upload the binaries to
# their final locations. The upload part requires credentials that should only
# be available to org-members.
##############################################################################
binary_populate_env: &binary_populate_env
  name: Set up env
  command: |
    if [[ -n "$CIRCLE_SHA1" ]]; then
      # we are on a PR or on a master-merge, but not on a timed build
      git_url="https://raw.githubusercontent.com/pytorch/pytorch/$CIRCLE_SHA1"
    else
      # scheduled nightly binary builds. These run at 05:05 UTC every day. 
      last_commit="$(git rev-list --before "$(date -u +%Y-%m-%d) 05:00" --max-count 1 HEAD)"
      git_url="https://raw.githubusercontent.com/pytorch/pytorch/$last_commit"
    fi
    curl -s "$git_url/.circleci/scripts/binary_populate_env.sh" -o "binary_populate_env.sh"
    cat "binary_populate_env.sh"
    source "binary_populate_env.sh"

binary_checkout: &binary_checkout
  name: Checkout
  command: |
    if [[ -n "$CIRCLE_SHA1" ]]; then
      # we are on a PR or on a master-merge, but not on a timed build
      git_url="https://raw.githubusercontent.com/pytorch/pytorch/$CIRCLE_SHA1"
    else
      # scheduled nightly binary builds. These run at 05:05 UTC every day. 
      last_commit="$(git rev-list --before "$(date -u +%Y-%m-%d) 05:00" --max-count 1 HEAD)"
      git_url="https://raw.githubusercontent.com/pytorch/pytorch/$last_commit"
    fi
    curl -s "$git_url/.circleci/scripts/binary_checkout.sh" -o "binary_checkout.sh"
    cat "binary_checkout.sh"
    source "binary_checkout.sh"

binary_install_miniconda: &binary_install_miniconda
  name: Install miniconda
  no_output_timeout: "1h"
  command: |
    if [[ -n "$CIRCLE_SHA1" ]]; then
      # we are on a PR or on a master-merge, but not on a timed build
      git_url="https://raw.githubusercontent.com/pytorch/pytorch/$CIRCLE_SHA1"
    else
      # scheduled nightly binary builds. These run at 05:05 UTC every day. 
      last_commit="$(git rev-list --before "$(date -u +%Y-%m-%d) 05:00" --max-count 1 HEAD)"
      git_url="https://raw.githubusercontent.com/pytorch/pytorch/$last_commit"
    fi
    curl -s "$git_url/.circleci/scripts/binary_install_miniconda.sh" -o "binary_install_miniconda.sh"
    cat "binary_install_miniconda.sh"
    source "binary_install_miniconda.sh"

# This section is used in the binary_test and smoke_test jobs. It expects
# 'binary_populate_env' to have populated /home/circleci/project/env and it
# expects another section to populate /home/circleci/project/ci_test_script.sh
# with the code to run in the docker
binary_run_in_docker: &binary_run_in_docker
  name: Run in docker
  command: |
    if [[ -n "$CIRCLE_SHA1" ]]; then
      # we are on a PR or on a master-merge, but not on a timed build
      git_url="https://raw.githubusercontent.com/pytorch/pytorch/$CIRCLE_SHA1"
    else
      # scheduled nightly binary builds. These run at 05:05 UTC every day. 
      last_commit="$(git rev-list --before "$(date -u +%Y-%m-%d) 05:00" --max-count 1 HEAD)"
      git_url="https://raw.githubusercontent.com/pytorch/pytorch/$last_commit"
    fi
    curl -s "$git_url/.circleci/scripts/binary_run_in_docker.sh" -o "binary_run_in_docker.sh"
    cat "binary_run_in_docker.sh"
    source "binary_run_in_docker.sh"
