      # Warning: indentation here matters!

      # Pytorch MacOS builds
      - pytorch_windows_build:
          requires:
            - setup
      - pytorch_windows_test:
          requires:
            - setup
            - pytorch_windows_build
