version: 2.1
jobs:
  build:
    resource_class: pytorch/amd-gpu
    machine: true
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
