version: 2.1

jobs:
  docker_build_job:
    parameters:
      image_name:
        type: string
        default: ""
    machine:
      image: ubuntu-1604:201903-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: build_docker_image_<< parameters.image_name >> ## don't change job prefix, build_docker.sh use the pattern
          no_output_timeout: "1h"
          command: |
            set +x
            export AWS_ACCESS_KEY_ID=${CIRCLECI_AWS_ACCESS_KEY_FOR_ECR_READ_WRITE_V4}
            export AWS_SECRET_ACCESS_KEY=${CIRCLECI_AWS_SECRET_KEY_FOR_ECR_READ_WRITE_V4}
            set -x
            cd .circleci/docker && ./build_docker.sh

workflows:
  build:
    jobs:
      - docker_build_job:
          image_name: "pytorch-linux-xenial-py3.6-gcc7"
