version: 2.1

jobs:
  docker_build_job:
    parameters:
      image_name:
        type: string
        default: ""
    machine:
      image: ubuntu-1604:201903-01
    resource_class: large
    environment:
      IMAGE_NAME: << parameters.image_name >>
    steps:
      - checkout
      - run:
          name: build_docker_image_<< parameters.image_name >>
          no_output_timeout: "1h"
          command: |
            set +x
            export AWS_ACCESS_KEY_ID=${CIRCLECI_AWS_ACCESS_KEY_FOR_DOCKER_BUILDER_V1}
            export AWS_SECRET_ACCESS_KEY=${CIRCLECI_AWS_SECRET_KEY_FOR_DOCKER_BUILDER_V1}
            set -x
            cd .circleci/docker && ./build_docker.sh

workflows:
  build:
    jobs:
      - docker_build_job:
          image_name: "pytorch-linux-bionic-clang9-thrift-llvmdev"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-cuda10-cudnn7-py3-gcc7"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-cuda10.1-cudnn7-py3-gcc7"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-cuda8-cudnn7-py2"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-cuda8-cudnn7-py3"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-cuda9-cudnn7-py2"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-cuda9-cudnn7-py3"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-cuda9.2-cudnn7-py3-gcc7"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-py2.7.9"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-py2.7"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-py3-clang5-android-ndk-r19c"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-py3-clang5-asan"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-py3.5"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-py3.6-clang7"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-py3.6-gcc4.8"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-py3.6-gcc5.4"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-py3.6-gcc7.2"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-py3.6-gcc7"
      - docker_build_job:
          image_name: "pytorch-linux-xenial-pynightly"
