version: 2.1

parameters:
  run_binary_tests:
    type: boolean
    default: false
  run_build:
    type: boolean
    default: true
  run_master_build:
    type: boolean
    default: false
  run_slow_gradcheck_build:
    type: boolean
    default: false

jobs:
  test:
    docker:
      - image: circleci/python:3
    steps:
      - run:
          name: Output environment variables
          command: env | grep CIRCLE

workflows:
  binary_builds:
    when: << pipeline.parameters.run_binary_tests >>
    jobs:
      - test
  build:
    jobs:
      - test
