name: Get Build Branch

description: Get build branch to use

runs:
  using: composite
  steps:
    - name: Get branch to use for building
      id: check_step
      shell: bash -e -l {0}
      run: |
        if [[ "${GITHUB_EVENT_NAME}" == 'push' && "${GITHUB_REF_NAME}" == *-rc[0-9]* ]]; then
          raw=$(git branch -r --contains "${GITHUB_REF_NAME}")
          REPO_BRANCH=${raw##*/}
          echo "REPO_BRANCH=release/${REPO_BRANCH}" >> $GITHUB_ENV
          echo "Branch is release/$REPO_BRANCH."
        elif [[ "${GITHUB_EVENT_NAME}" == 'push' && "${GITHUB_REF_NAME}" == *ciflow* ]]; then
          echo "REPO_BRANCH=$(python3 ${GITHUB_ACTION_PATH}/../../scripts/get_ciflow_base_ref.py)" >> "${GITHUB_ENV}"
        else
          echo "REPO_BRANCH=main" >> $GITHUB_ENV
        fi
