{% set version = "0.8.dev" %}

package:
  name: caffe2
  version: {{ version }}

source:
  path: ../../..

build:
  number: 0
  string: py{{py}}
  skip: True  # [win]
  script_env:
    - CONDA_CAFFE2_CMAKE_ARGS
    - BUILD_WITH_CUDA

requirements:
  build:
    - cmake
    - future
    - numpy
    - python
    - six
    # build packages here
  run:
    - future
    - numpy
    - protobuf
    - python
    - six
    # run packages here

test:
  # test packages here
  imports:
    - caffe2.python.core

about:
  home: https://caffe2.ai/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Caffe2 is a lightweight, modular, and scalable deep learning framework.

extra:
  recipe-maintainers:
    - pjh5
