name: android-tests

on:
  workflow_call:
    inputs:
      test-matrix:
        required: true
        type: string
        description: |
          A JSON description of what configs to run later on.

defaults:
  run:
    shell: bash -e -l {0}

jobs:
  build-and-test:
    strategy:
      matrix: ${{ fromJSON(inputs.test-matrix) }}
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      # [see note: pytorch repo ref]
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@master

      - name: Setup miniconda
        uses: pytorch/test-infra/.github/actions/setup-miniconda@main
        with:
          python-version: 3.8
          environment-file: .github/requirements/conda-env-${{ runner.os }}-${{ runner.arch }}

      - name: Select all requested test configurations
        id: filter
        uses: ./.github/actions/filter-test-configs
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-matrix: ${{ inputs.test-matrix }}

      - name: Build PyTorch Android
        if: steps.filter.outputs.is-test-matrix-empty == 'False' || inputs.test-matrix == ''
        id: build
        run: |
          # Install NDK 21 after GitHub update
          # https://github.com/actions/virtual-environments/issues/5595
          ANDROID_ROOT="/usr/local/lib/android"
          ANDROID_SDK_ROOT="${ANDROID_ROOT}/sdk"
          SDKMANAGER="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
          echo "y" | ${SDKMANAGER} "ndk;21.4.7075529"

          export ANDROID_NDK="${ANDROID_SDK_ROOT}/ndk-bundle"
          ln -sfn ${ANDROID_SDK_ROOT}/ndk/21.4.7075529 ${ANDROID_NDK}

          echo "CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname "$(which conda)")/../"}" >> "${GITHUB_ENV}"
          ${CONDA_RUN} ./scripts/build_pytorch_android.sh x86

      - name: Run tests
        if: steps.build.conclusion && steps.build.conclusion != 'skipped'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 25
          script: ./android/run_tests.sh
