name: Build Test

on:
  pull_request:
    types: [opened, synchronize, reopened, unassigned]
  workflow_call:
    secrets:
        token:
          required: true

jobs:
  call-workflow-build-linux-wheels:
    # uses: pytorch/pytorch/.github/workflows/build_linux_wheels.yml@master
    runs-on: linux.2xlarge 
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."