name: Cancel redundant workflows
on:
  workflow_run:
    types:
      - requested
    workflows:
      - clang-format
      - Lint
      - Test tools

jobs:
  cancel:
    # We do not want to cancel reruns on master
    if: github.event.workflow_run.head_branch != 'master'
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel duplicate workflow runs
        uses: potiuk/cancel-workflow-runs@v4_8
        with:
          cancelMode: duplicates
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
