name: setup.py Python 2 compatability

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  check-compat:
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.x
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@v2
      - name: Attempt to run setup.py
        run: |
          python setup.py | grep "Python 2 has reached end-of-life and is no longer supported by PyTorch."
