name: Check mergability and dependencies for ghstack prs

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-regex:
    runs-on: ubuntu-latest
    outputs:
      regex-match: ${{ steps.regex-match.outputs.match }}
    steps:
      - uses: actions/checkout@v2

      - id: regex-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.head_ref }}
          regex: '^(gh/[^/]+/[0-9]+/)head$'

  pr-dependencies-check:
    needs: check-regex
    if: ${{ needs.check-regex.outputs.regex-match != '' }}
    uses: pytorch/test-infra/.github/workflows/pr-dependencies-check.yml@9ba44887a5bbe803c735fb392651068056e678b5
    with:
      pr_number: ${{ github.event.pull_request.number }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
