name: docker-builds

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
      - landchecks/*
    paths:
      - .ci/docker/**
      - .github/workflows/docker-builds.yml
      - .github/workflows/_docker-builds.yml
      - .lintrunner.toml
  schedule:
    - cron: 1 3 * * 3

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

env:
  ALPINE_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine
  AWS_DEFAULT_REGION: us-east-1

permissions: read-all

jobs:
  build-docker-images:
    if: github.repository_owner == 'pytorch'
    name: build-docker-images
    uses: ./.github/workflows/_docker-builds.yml
    with:
      always-rebuild: true
      push-to-ghcr: ${{ github.event_name == 'push' && true || false }}
      docker-build-matrix: |
        { include: [
          { "docker-image-name": "pytorch-linux-focal-cuda12.4-cudnn9-py3-gcc9" },
          { "docker-image-name": "pytorch-linux-focal-cuda12.4-cudnn9-py3-gcc9-inductor-benchmarks" },
          { "docker-image-name": "pytorch-linux-focal-cuda12.4-cudnn9-py3.12-gcc9-inductor-benchmarks" },
          { "docker-image-name": "pytorch-linux-focal-cuda12.1-cudnn9-py3-gcc9" },
          { "docker-image-name": "pytorch-linux-focal-cuda12.1-cudnn9-py3-gcc9-inductor-benchmarks" },
          { "docker-image-name": "pytorch-linux-focal-cuda12.1-cudnn9-py3.12-gcc9-inductor-benchmarks" },
          { "docker-image-name": "pytorch-linux-focal-cuda11.8-cudnn9-py3-gcc9" },
          { "docker-image-name": "pytorch-linux-focal-py3.9-clang10" },
          { "docker-image-name": "pytorch-linux-focal-py3.11-clang10" },
          { "docker-image-name": "pytorch-linux-focal-py3.12-clang10" },
          { "docker-image-name": "pytorch-linux-focal-py3.13-clang10" },
          { "docker-image-name": "pytorch-linux-focal-rocm-n-1-py3" },
          { "docker-image-name": "pytorch-linux-focal-rocm-n-py3" },
          { "docker-image-name": "pytorch-linux-jammy-cuda11.8-cudnn9-py3.9-clang12" },
          { "docker-image-name": "pytorch-linux-jammy-py3.9-gcc11" },
          { "docker-image-name": "pytorch-linux-jammy-py3.9-gcc11-inductor-benchmarks" },
          { "docker-image-name": "pytorch-linux-jammy-py3.12-halide" },
          { "docker-image-name": "pytorch-linux-jammy-xpu-2024.0-py3" },
          { "docker-image-name": "pytorch-linux-jammy-py3-clang15-asan" },
          { "docker-image-name": "pytorch-linux-jammy-py3-clang18-asan" },
          { "docker-image-name": "pytorch-linux-focal-py3-clang10-onnx" },
          { "docker-image-name": "pytorch-linux-focal-linter" },
          { "docker-image-name": "pytorch-linux-jammy-cuda11.8-cudnn9-py3.9-linter" },
          { "docker-image-name": "pytorch-linux-jammy-py3-clang12-executorch" },
          { "docker-image-name": "pytorch-linux-jammy-py3.12-triton-cpu" },
          { "docker-image-name": "pytorch-linux-jammy-aarch64-py3.10-gcc11", "runner": "linux.arm64.2xlarge" },
          { "docker-image-name": "pytorch-linux-jammy-aarch64-py3.10-gcc11-inductor-benchmarks", "runner": "linux.arm64.m7g.4xlarge", "timeout-minutes": 600 },
        ]}
    secrets: inherit
