name: inductor

on:
  push:
    branches:
      - master
      - main
    tags:
      - ciflow/inductor/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  linux-bionic-cuda11_8-py3_10-gcc7-inductor-build-gcp:
    name: cuda11.8-py3.10-gcc7-sm89
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-bionic-cuda11.8-py3.10-gcc7-sm89
      docker-image-name: pytorch-linux-bionic-cuda11.8-cudnn8-py3-gcc7
      cuda-arch-list: '8.9'
      test-matrix: |
        { include: [
          { config: "inductor_torchbench_smoketest_perf", shard: 1, num_shards: 1, runner: "linux.gcp.l4" },
        ]}

  linux-bionic-cuda11_8-py3_10-gcc7-inductor-test-gcp:
    name: cuda11.8-py3.10-gcc7-sm89
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-bionic-cuda11_8-py3_10-gcc7-inductor-build-gcp
    with:
      build-environment: linux-bionic-cuda11.8-py3.10-gcc7-sm89
      docker-image: ${{ needs.linux-bionic-cuda11_8-py3_10-gcc7-inductor-build-gcp.outputs.docker-image }}
      test-matrix: ${{ needs.linux-bionic-cuda11_8-py3_10-gcc7-inductor-build-gcp.outputs.test-matrix }}
      use-gha: anything-non-empty-to-use-gha

  linux-focal-cpu-py3_8-gcc7-inductor-build:
    name: linux-focal-cpu-py3.8-gcc7-inductor
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-focal-py3_8-gcc7-build
      docker-image-name: pytorch-linux-focal-py3.8-gcc7
      test-matrix: |
        { include: [
          { config: "inductor_huggingface_cpu_accuracy", shard: 1, num_shards: 1, runner: "linux.4xlarge" },
          { config: "inductor_timm_cpu_accuracy", shard: 1, num_shards: 2, runner: "linux.4xlarge" },
          { config: "inductor_timm_cpu_accuracy", shard: 2, num_shards: 2, runner: "linux.4xlarge" },
          { config: "inductor_torchbench_cpu_accuracy", shard: 1, num_shards: 1, runner: "linux.4xlarge" },
        ]}
