name: Lint

on:
  push:
    branches:
    - master
  pull_request:

# note [local lint]
# LOCAL_FILES in the jobs below is intended to be filled by local (i.e. on a
# developer's machine) job in tools/actions_local_runner.py to pass only the
# changed files to whatever tool is consuming the files. This helps speed up
# local lints while keeping the linting code unified between local / CI.

jobs:
  quick-checks:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
      - name: test secrets
        run: |
          printenv | sort
          echo ${MY_TEST_SECRET}
