name: Run MPS tets
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  run_mps_test:
    name: "Run MPS tests on x86"
    runs-on: macos12.3-x86
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PyTorch
        env:
          ENV_NAME: conda-test-env-${{ github.run_id }}
          PY_VERS: 3.9
        run: |
          . ~/miniconda3/etc/profile.d/conda.sh
          set -ex
          conda create -yp ${ENV_NAME} python=${PY_VERS} numpy expecttest
          conda run -p ${ENV_NAME} python3 -mpip install torch --pre --extra-index-url=https://download.pytorch.org/whl/nightly

      - name: Run MPS tests
        env:
          ENV_NAME: conda-test-env-${{ github.run_id }}
        run: |
          . ~/miniconda3/etc/profile.d/conda.sh
          set -ex
          conda run --cwd test -p ${ENV_NAME} python3 test_mps.py -v

      - name: Cleanup conda env
        env:
          ENV_NAME: conda-test-env-${{ github.run_id }}
        run: |
          . ~/miniconda3/etc/profile.d/conda.sh
          conda env remove -p ${ENV_NAME}