name: pull

on:
  pull_request:
    branches-ignore:
      - nightly
  push:
    branches:
      - main
      - release/*
      - landchecks/*
  workflow_dispatch:
  schedule:
    - cron: 29 8 * * *  # about 1:29am PDT

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  linux-jammy-py3_8-gcc11-build:
    name: linux-jammy-py3.8-gcc11
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-jammy-py3.8-gcc11
      docker-image-name: pytorch-linux-jammy-py3.8-gcc11
      test-matrix: |
        { include: [
          { config: "docs_test", shard: 1, num_shards: 1,  runner: "linux.2xlarge" },
        ]}

  macos-12-py3-x86-64-build:
    name: macos-12-py3-x86-64
    uses: ./.github/workflows/_mac-build.yml
    with:
      build-environment: macos-12-py3-x86-64
      xcode-version: "13.3.1"
      runner-type: macos-12-xl
      build-generates-artifacts: true
      sccache-use-gha: true
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1, runner: "macos-12" },
        ]}
