name: pull

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - release/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  macos-11-py3-x86-64-build:
    name: macos-11-py3-x86-64
    uses: ./.github/workflows/_mac-build.yml
    with:
      build-environment: macos-11-py3-x86-64
      xcode-version: "12.4"
      runner-type: macos-11
      build-generates-artifacts: true
    secrets:
      MACOS_SCCACHE_S3_ACCESS_KEY_ID: ${{ secrets.MACOS_SCCACHE_S3_ACCESS_KEY_ID }}
      MACOS_SCCACHE_S3_SECRET_ACCESS_KEY: ${{ secrets.MACOS_SCCACHE_S3_SECRET_ACCESS_KEY }}

  macos-11-py3-x86-64-test:
    name: macos-11-py3-x86-64
    uses: ./.github/workflows/_mac-test.yml
    needs: macos-11-py3-x86-64-build
    with:
      build-environment: macos-11-py3-x86-64
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 2, runner: "macos-11" },
          { config: "default", shard: 2, num_shards: 2, runner: "macos-11" },
        ]}
    secrets:
      AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID: ${{ secrets.AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID }}
      AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY: ${{ secrets.AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY }}
