name: pull

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - release/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  linux-focal-py3_7-gcc7-build:
    name: linux-focal-py3.7-gcc7
    uses: ./.github/workflows/_linux-build.yml
    with:
      foobar-token: ${{ secrets.GITHUB_TOKEN }}
      build-environment: linux-focal-py3.7-gcc7
      docker-image-name: pytorch-linux-focal-py3.7-gcc7

