name: Build PyTorch nightly docker and push to GitHub Container Registry
on:
  schedule:
    # Push the nightly docker daily at 1 PM UTC
    - cron: '0 13 * * *'
  # Have the ability to trigger this job manually using the API as well
  workflow_dispatch:

jobs:
  build-publish-docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          bash .github/scripts/build_publish_nightly_docker.sh
