name: Python package

on: 
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: flake8
        uses: suo/flake8-github-action@releases/v0.0.2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
