name: Repository Dispatch

on:
  pull_request:
    types: [opened, synchronize, reopened, unassigned]
  repository_dispatch:

jobs:
  workflow-test:
    runs-on: linux.2xlarge 
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      