name: TorchBench CI (pytorch-linux-py3.7-cu102)
on:
  pull_request:

env:
  PR_NUM: ${{ github.event.number }}
  PR_BODY: ${{ github.event.pull_request.body }}
  PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
  PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}

jobs:
  run-torchbench:
    # We don't accept running on non-pytorch repos because of security concerns
    # Only run the job when the body contains magic word "RUN_TORCHBENCH:"
    if: ${{ github.repository_owner == 'pytorch' && contains(github.event.pull_request.body, 'RUN_TORCHBENCH:') }}
    runs-on: [self-hosted, bm-runner]
    steps:
      - name: Checkout PyTorch
        uses: actions/checkout@v2
        with:
          path: pytorch
      - name: Checkout TorchBench
        uses: actions/checkout@v2
        with:
          repository: pytorch/benchmark
          path: benchmark
      - name: Create conda environment
        run: |
          conda create -y -n pr-ci python=3.7
          . ${HOME}/miniconda3/etc/profile.d/conda.sh
          conda activate pr-ci
          conda install -y numpy=1.17 requests=2.22 ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six dataclasses pillow pytest tabulate
      - name: Run TorchBench
        run: |
          PR_BODY_FILE=/tmp/pr-body.txt
          echo "$PR_BODY" > ${PR_BODY_FILE}
          . ${HOME}/miniconda3/etc/profile.d/conda.sh
          conda activate pr-ci
          python3 pytorch/.github/scripts/run_torchbench.py \
                  --pytorch-path "${PWD}"/pytorch \
                  --torchbench-path "${PWD}"/benchmark \
                  --pr-num "$PR_NUM" \
                  --pr-base-sha "$PR_BASE_SHA" \
                  --pr-head-sha "$PR_HEAD_SHA" \
                  --pr-body "$PR_BODY_FILE"
      - name: Remove conda environment
        run: |
          conda env remove --name pr-ci
