name: Sync Distributed Folder

on:
  #push:
  #  branches:
  #    - 'main'
  #  paths:
  #    - 'torch/distributed/**'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/scripts/sync_distributed_folder_prototype.sh'
      - '.github/workflows/sync_distributed_folder_prototype.yml'

env:
  WITH_PUSH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'fbcode/pytorch-stable-prototype'
      - run: .github/scripts/sync_distributed_folder_prototype.sh
