name: weekly

on:
  schedule:
    # Mondays at 7:37am UTC = 12:27am PST
    # Choose a random time near midnight PST because it may be delayed if there are high loads
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: 37 7 * * 1
  workflow_dispatch:

jobs:
  update-xla-commit-hash:
    runs-on: ubuntu-latest
    environment: update-commit-hash
    uses: ./.github/actions/update-commit-hash
    with:
      repo-name: xla
      branch: master
      updatebot-token: ${{ secrets.UPDATEBOT_TOKEN }}
      pytorchbot-token: ${{ secrets.GH_PYTORCHBOT_TOKEN }}

  update-triton-commit-hash:
    runs-on: ubuntu-latest
    environment: update-commit-hash
    uses: ./.github/actions/update-commit-hash
    with:
      repo-owner: openai
      repo-name: triton
      branch: main
      pin-folder: .ci/docker/ci_commit_pins
      updatebot-token: ${{ secrets.UPDATEBOT_TOKEN }}
      pytorchbot-token: ${{ secrets.GH_PYTORCHBOT_TOKEN }}
