name: Reuse workflow no concurrency

on:
  pull_request:
    types: [opened, synchronize, reopened, unassigned]
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  workflow-test:
    runs-on: linux.2xlarge 
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      